### ISSUE TITLE
Missing maxi-nerdle equations

### ISSUE THREAD

**Issue by rbtying** [PedroKKr/Nerdle-Equations#1]
I think your script is missing a few maxi-nerdle equations, probably due to floating-point inaccuracy:

for example:

`11/3-5/3=2` is a valid maxi-nerdle equation

**Comment by pedrokkrause** [comment]
I guess you are right, which is strange, because equations like `11/3-2/3=3` are present. I think I'll correct the code and regenerate the equations.

**Comment by rbtying** [comment]
```
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 11/3
3.6666666666666665
>>> 11/3-5/3
1.9999999999999998
>>> 11/3-2/3
3.0
>>>
```

IEEE754 bites us again :)

Here's my generated list: https://github.com/rbtying/maxi-nerdle-solver/blob/main/nerdle-solver/maxi_nerdle.txt

**Comment by pedrokkrause** [comment]
Thank you for sharing! It seems that only very few equations were not considered, at least. 
May I ask, out of curiosity, how much time did it take for your rust script to generate the equations?

**Comment by rbtying** [comment]
My script takes a couple minutes? Not nearly as fast as the C version, mostly because I used a parsing library for the evaluator. It can probably be optimized quite a bit

**Comment by pedrokkrause** [comment]
I made a new maxi equation generator script and generated all the equations again, by using the fractions module. I also considered another rule, which is to allow the minus sign after the parenthesis, that is, "(-", which adds about 20,000 more equations. We can't know for sure which rules Nerdle uses for Maxi, but it felt reasonable to consider this, and it's better to have equations in excess than missing equations.
